### ISSUE TITLE
Знайти фото Нового Роздолу в Інтернеті

### ISSUE THREAD

**Issue by Mrkiyan21** [Mrkiyan21/pr4_2021#1]
Знайти фото в інтернеті

**Comment by nrpk2** [comment]
Тримай водонапірну башту: http://photos.wikimapia.org/p/00/06/96/28/15_big.jpg

**Comment by nrpk2** [comment]
![image](https://user-images.githubusercontent.com/5570074/141064502-a9f18536-e760-48f8-80d9-13bc739cab7d.png)

**Comment by nrpk2** [comment]
А знайди мені фото коледжу в Інтернеті

**Comment by Mrkiyan21** [comment]
![image](https://user-images.githubusercontent.com/94036142/141064771-4f3d3f3b-1055-437a-a140-c789a9ff25ea.png)

**Comment by Mrkiyan21** [comment]
Зображення знайдено
